### ISSUE TITLE
[Bug]: Add BrazeKitCompat to the README

### ISSUE THREAD

**Issue by jesus-mg-ios** [braze-inc/braze-swift-sdk#139]
### Platform

iOS

### Platform Version

IOS 15

### Braze SDK Version

9.00

### Xcode Version

15.0

### Computer Processor

Apple (M1)

### Repro Rate

-

### Steps To Reproduce

Example:
  1. Add `braze.logCustomEvent(name: "custom_event")` in `AppDelegate.swift`.
  2. Run the app.

### Expected Behavior

-

### Actual Incorrect Behavior

-

**Comment by jerielng** [comment]
Hey @jesus-mg-ios, thanks for submitting this feedback. If I understand correctly, you are requesting that we add `BrazeKitCompat` to the [list of libraries](https://github.com/braze-inc/braze-swift-sdk?tab=readme-ov-file#libraries) in the readme? We don't specifically list this out since it is provided mainly as a migration layer if you are moving over from the legacy Appboy iOS SDK. You can reference the usage here in the [migration guide](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide/), which is linked in the readme.
