### ISSUE TITLE
[Bug]: Adding alias event is not trigger immediately

### ISSUE THREAD

**Issue by JAIRMG** [braze-inc/braze-swift-sdk#149]
### Platform

iOS

### Platform Version

iOS 18

### Braze SDK Version

11.4.0

### Xcode Version

Xcode 16.0

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Hi, I noticed that `brazeSDK.user.addAlias(ALIAS_NAME, ALIAS_LABEL)` is not triggering the event immediately. If I kill the app and open it again I see this event as part of the events array in `{domain}/api/v3/data`. The interesting part is that registering the device with `brazeSDK.notifications.register(deviceToken: deviceToken)` does happen immediately. 

I don't think that is the expected behaviour. Could it be that the SDK is waiting for a batch of events to send them at once? Can I change the priority of certain events? 

### Expected Behavior

Event sent immediately 

### Actual Incorrect Behavior

Event sent after opening app again as part of the events array together with other events

**Comment by jerielng** [comment]
Hi @JAIRMG, what you are seeing is expected behavior. Calling `addAlias` adds that event to a queue (as you are seeing in that events array), and that queue is only flushed to the network based on what you have configured for your [`flushInterval`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/configuration-swift.class/api-swift.class/flushinterval), so your theory on batched events is correct.

The device token flushes immediately because the SDK explicitly accounts for that to ensure that push notifications are registered as quickly as possible, but this is a special case and does not apply to most other data that flows through the `/v3/data` endpoint for the reason described above.

If you would like more control over this, you can call [`requestImmediateDataFlush`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/requestimmediatedataflush()) after calling `addAlias` to immediately send that event. Or, to handle this more broadly, you can also configure a lower flush interval.
