### ISSUE TITLE
[Bug]: Unexpected warnings generating dSym

### ISSUE THREAD

**Issue by carlosnaguilera** [braze-inc/braze-swift-sdk#31]
### Platform

iOS

### Platform Version

iOS 16.2

### Braze SDK Version

5.8.0

### Xcode Version

Xcode 14.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

On a minimal migration from appboy sdk to swift sdk, after replacing all the imports. When we compile the app we get some unexpected warnings related to dSym generation

### Expected Behavior

No warning about dSym generation. Just deprecation warnings should appear

### Actual Incorrect Behavior

Warnings appear

![Screenshot 2022-12-30 at 14 02 49](https://user-images.githubusercontent.com/1766166/210072978-0f6fec56-3c22-4b7a-bec1-798ca560e322.png)

### Additional Information

Cleaning build folder, closing project and restarting Xcode don't fix the issue

**Comment by hokstuff** [comment]
Hi @carlosnaguilera,

You noted above that you are migrating from the `appboy-ios-sdk` to the `braze-swift-sdk`. To clarify:
1. Did you import both libraries `BrazeKitCompat` and `BrazeUICompat` and have you followed the full [Migration Guide](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide/)?
2. Do these warnings block your project from compiling and running?
3. In your warning above, it shows a specific user name after `/Users/`. Can you check in your project if that hardcoded user's string appears, since it's possible that it should have a generic `{USER}` macro instead

**Comment by carlosnaguilera** [comment]
Sorry for the delay answering you. I was on Christmas holidays. So, regarding you questions:

1. Yes
2. Kind of. We treat warnings as errors, so from that point of view, it blocks us. We could stop treating warnings as errors, but it is not ideal
3. I'm afraid that that user is a Braze software engineer 😬. He's one of the five contributors of this repo! 😅

**Comment by hokstuff** [comment]
Hi @carlosnaguilera,

We have identified a possible fix around these warnings and will respond back here once it is ready to be tested to see if it solves the issue for you. Stay tuned for updates - thanks!

**Comment by hokstuff** [comment]
Hi @carlosnaguilera,

We have released Swift SDK [version 5.9.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.9.0) which addresses this issue. Please let us know if you still see the warnings after updating to that version - thanks!
