### ISSUE TITLE
[Feature]: CC - Classic Image Card - imageAspectRatio (?)

### ISSUE THREAD

**Issue by louisebehrenfors-s** [braze-inc/braze-swift-sdk#40]
### What problem are you facing?

Hi! 
For the cards **Captioned Card** and **Banner Card** we get the `imageAspectRatio` for the image to be shown. 
This however, is not in the Classic Image Card which would be preferred to have, since it helps with doing the layout of the view we wanna show the image in.

### Workarounds

It will not look as smooth without the ratio. Especially when loading the image url and having a placeholder. Would be very appreciated having the ratio beforehand. 

### Ideal Solution

Provide `imageAspectRatio` for the Classic Image Card.

**Comment by jerielng** [comment]
Hi @louisebehrenfors-s! The `imageAspectRatio` property isn't supported for Classic Image Cards since they are meant to be used as icons and require a 1:1 aspect ratio according to our [Braze specifications](https://www.braze.com/docs/user_guide/message_building_by_channel/content_cards/creative_details#:~:text=The%20classic%20card%20is%20great,at%20a%201%3A1%20ratio).

As an alternative, we would recommend exploring some of the other options you mentioned, like banner or captioned image cards, to better fit your use case. Moreover, if you have specific UI needs that aren't addressed with the out-of-the-box types, you can explore some of the customization paths detailed [here](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/content-cards-customization).

**Comment by hokstuff** [comment]
Closing out this issue as per the response above ^

If you have any further questions or feature requests, please contact our Support team or your CSM. Thanks!
