### ISSUE TITLE
[Bug]: Braze not loading resources/Localization

### ISSUE THREAD

**Issue by Oaseru17** [braze-inc/braze-swift-sdk#44]
### Platform

iOS

### Platform Version

iO 15.5

### Braze SDK Version

5.10.0

### Xcode Version

14.1

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Step up 

1. Braze.Configuration(.. with the required inputs)

### Expected Behavior

Braze can find resources

### Actual Incorrect Behavior

[braze] Error: Unable to find resources bundle, cannot load localizations and acknowledgments

**Comment by lowip** [comment]
Hi @Oaseru17,

Could you provide more information about your setup? Unless integrating the SDK manually, there shouldn't be any extra step to ensure that the SDK is able to locate the resources / localization files.

**Comment by victor-sarda** [comment]
Hi @lowip,

I'm answering on behalf of @Oaseru17,

At JustEat we use Tuist to generate our app project, and it doesn't use a native implementation of SPM. It handles resources and creates bundles automatically. I see you've hardcoded bundle names for SPM [here](https://github.com/braze-inc/braze-swift-sdk/blob/main/Sources/BrazeUI/Resources.swift#L9).

The issue we have here is that Tuist uses a slightly different name for resource bundle it creates, for instance, with BrazeUI it will use `braze_swift_sdk_BrazeUI` (instead of the `braze-swift-sdk_BrazeUI`).

The main problem is that hardcoded bundle names for SPM aren't reliable. We had a similar issue when we migrated our modularised code base from CocoaPods to SPM, we wanted to keep support for both so we found a workaround. We created Bundle extensions like so:

```swift
extension Bundle {
    var myModuleName: Bundle {
        #if SWIFT_PACKAGE
            return Bundle.module
        #else
            // return hard coded name for Cocoapods
       #endif
}
```

The `SWIFT_PACKAGE` pre-processor macro is available by default when you build from a Package so it's safe to use.
I think an update like this in the BrazeUI `Resources.swift` file would fix the issue:

```swift
extension Bundle {
    var resourceBundle: Bundle? {
#if SWIFT_PACKAGE
        return .module
#else
        let bundleNames = [
            // Cocoapods resources
            "BrazeUI",
        ]
        
        let candidates = [
            // Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,
            // Bundle should be present here when the package is linked into a framework.
            Bundle(for: BundleFinder.self).resourceURL,
            // For command-line tools.
            Bundle.main.bundleURL,
        ]
        
        for bundleName in bundleNames {
            for candidate in candidates {
                let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
                if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                    return bundle
                }
            }
        }
        
        print(
            "[braze] Error: Unable to find UI resources bundle, cannot load localizations and acknowledgments"
        )
        return nil
#endif
    }
}
```

@lowip please let me know if that make sense 🙏

**Comment by lowip** [comment]
Hi @victor-sarda,

Thanks for the context, your explanation makes sense. Unfortunately, we can't rely on the `SWIFT_PACKAGE` preprocessor value to guarantee the existence of `Bundle.module`. This is due to the fact that we also support binary XCFrameworks for `BrazeUI`.

Nonetheless, I think we can provide an alternative API that should unblock you. Something like:

```swift
// Root level of BrazeUI

/// The override bundle BrazeUI uses to load resources (default: `nil`).
public var overrideResourceBundle: Bundle?
```

This way, you could override the bundle with the one generated by Tuist:
```swift
// In `AppDelegate.didFinishLaunching:...`

BrazeUI.overrideResourceBundle = Bundle(url: /* tuist-generated bundle url */)
```

If that works for you, we should be able to ship an update fairly soon.

**Comment by victor-sarda** [comment]
Hey @lowip,

Thanks for replying quickly. I understand the limitation with `SWIFT_PACKAGE` & binary xcframeworks. The proposed solution could work in theory and I'd be happy to try it 👍 

Would you be able to push the changes to a new branch so we can try it on our side?

Thanks!

**Comment by lowip** [comment]
Hey @victor-sarda, @Oaseru17

You should be able to test the change using the branch `brazeui-override-resources-bundles`. If this is working for you, this change will be added to the main branch as part of the next release.

With that branch, you can now write:
```swift
BrazeUI.overrideResourceBundle = Bundle(url: /* tuist-generated bundle url */)
```

**Comment by oriolpregona** [comment]
Hi @lowip, we are facing the exact same situation in our company (Braze 5.x.x migration + Tuist). Very nice timing for resolving this issue :)
I tried the suggested fix on the branch and this is the result:

Even though we did set that global `Bundle` before the init of Braze, the message still shows.
<img width="1063" alt="Screenshot 2023-03-03 at 12 40 38" src="https://user-images.githubusercontent.com/102145158/222712987-aabad504-e14e-42a2-a64e-79277fec6f16.png">

It's confusing because that breakpoint is never reaching the print statement.
<img width="684" alt="Screenshot 2023-03-03 at 12 41 27" src="https://user-images.githubusercontent.com/102145158/222712003-db5214b1-e19c-4734-936f-ee534b4ddc81.png">

Worth noting, this console error is reported right after I call `Braze(configuration:...)`, but the debugger won't stop there at that point, it will only stop a seconds later when Braze tries to access the resources again. This might a debugger issue, but this still doesn't explain why that error still appears.
Is your Braze init reaching for resources? Could that print statement come from another place too?

**Comment by lowip** [comment]
Hi @oriolpregona,

Thanks for testing the change. The error message you are currently seeing refers to the resources bundle used by our main `BrazeKit` module.
As the change seems to work for `BrazeUI` (as shown in the second snapshot), we're replicating it for `BrazeKit`.

Unfortunately, `BrazeKit` being distributed as a binary framework, we cannot provide a branch to test that behavior (to keep our repository small, our binary XCFrameworks are provided as Github releases artifacts).

We'll update here once the fix is publicly available.

**Comment by oriolpregona** [comment]
Hi @lowip,

Thanks for the update. I've got a few follow up questions :) 

Do you have a date in mind for that update, for us to plan the migration?
And what can we expect if we migrate without this fix? At the moment we use push notifications, logging and in-app messages. Would it break any of these? So far when testing, we didn't identify any issues related with the missing bundle.

In terms of the API changes, I imagine having this global variable is not the best approach you have in mind, perhaps being an option inside `Braze.Configuration`?

Thanks very much!

**Comment by lowip** [comment]
Hi @oriolpregona,

The change is merged in our private repo and will be part of the next release. We're planning to push it out later this week.

> And what can we expect if we migrate without this fix? At the moment we use push notifications, logging and in-app messages. Would it break any of these? So far when testing, we didn't identify any issues related with the missing bundle.

- BrazeKit
  - Push Notification with action buttons won't be localized (e.g. display `braze.push.action.accept` instead of `Accept`)
  - The post-click webview _no connection_ message won't be localized (display `braze.webview.no-connection` instead of `Cannot establish network connection. Please try again later.`)
- BrazeUI
  - Cannot display FontAwesome icons
  - Content Cards UI error message _We have no updates. Please check again later_ will display as `braze.content-cards.no-card.text`
  - Content Cards pin icon and image retry assets won't display
  - In-app message close button won't be localized (not user visible but used for accessibility / VoiceOver)
  - Slideup in-app messages won't display the chevron / arrow

> In terms of the API changes, I imagine having this global variable is not the best approach you have in mind, perhaps being an option inside `Braze.Configuration`?

There are currently a few reasons explaining why we'd rather keep it global:
- `BrazeUI` is loosely coupled with `BrazeKit` / `Braze` and only relies on some of its data models
  - This is done to ensure that our UI code remain modular / testable
  - The UI is not configurable by `Braze.Configuration`. Enabling that would require a breaking API change + tighter coupling 
- Our resources also contain licenses (if you wish to presents them in your application)
  - We don't want to require initializing a Braze instance to access them

For the time being, we'd rather keep similar APIs for both `BrazeKit` and `BrazeUI`:
```swift
BrazeKit.overrideResourceBundle = /* ... */
BrazeUI.overrideResourceBundle = /* ... */
```

**Comment by victor-sarda** [comment]
Hi @lowip,

Sorry for the delay. Thanks for pushing a fix, I'll try it asap and get back to you!

**Comment by hokstuff** [comment]
Hi @Oaseru17 @victor-sarda,

We have released the [Swift SDK version 5.11.1](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.11.1) which adds functionality that addresses this issue.

Thanks!

**Comment by victor-sarda** [comment]
Hi @hokstuff, thanks for letting us know, we actually planned to test it today 🎉

**Comment by victor-sarda** [comment]
Hi @hokstuff, the fix seems to work for `BrazeUI` but the issue still happens with `BrazeKit` `BrazeKit.overrideResourceBundle` doesn't seem to have any effect.

**Comment by victor-sarda** [comment]
Apologies, it's working when setting the bundle before initialising Braze!
