### ISSUE TITLE
[Bug]: BrazeNotificationService - Does not exist in the list of available frameworks

### ISSUE THREAD

**Issue by alexanderathan** [braze-inc/braze-swift-sdk#48]
### Platform

iOS

### Platform Version

iOS 14.0

### Braze SDK Version

5.11.0

### Xcode Version

14.2

### Computer Processor

Intel

### Repro Rate

100% of the time

### Steps To Reproduce

Hello there!

We are following [this guide](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b2-rich-push-notifications) for Rich Push Notifications integration in our app.

The BrazeKit is installed via CocoaPods. More specifically, with:
`pod 'BrazeKit', '5.11.0'`

We are unable to find BrazeNotificationService in General -> Frameworks & Libraries after pressing "+" button to add the framework in PushNotificationsServiceExtension.

Unfortunately, we cannot use Swift Package Manager.

### Expected Behavior

After installing BrazeKit via CocoaPods, we should be able to see the BrazeNotificationsService framework in the list of frameworks under "Frameworks & Libraries" section of a notification service extension.

### Actual Incorrect Behavior

BrazeNotificationService framework is not in the list of available frameworks under "Frameworks & Libraries" section of a notification service extension.

Thank you in advance for your time.

### Additional Information
![BrazeNotificationService](https://user-images.githubusercontent.com/19324963/222154849-57b139d5-4828-4a12-9926-11d54417dc0d.jpg)
_No response_

**Comment by jerielng** [comment]
Hi @alexanderathan, since you are integrating with CocoaPods, you'll have to add the `BrazeNotificationService` dependency to your notification service extension target in your Podfile.

Can you verify if adding the following to the root-level of your Podfile works:
```
target '<your-notification-extension-target>' do
  pod 'BrazeNotificationService'
end
```

If you happen to be using the `use_frameworks!` directive in your Podfile, you can try this:
```
target '<your-notification-extension-target>' do
  use_frameworks! :linkage => :static
  pod 'BrazeNotificationService'
end
```

For more context, this [thread](https://github.com/braze-inc/braze-flutter-sdk/issues/39) and this [thread](https://github.com/braze-inc/braze-swift-sdk/issues/35) provide some additional background information.

**Comment by alexanderathan** [comment]
H @jerielng, I was adding the extension's target in the Podfile as you mentioned, but my directive was `use_frameworks!` instead of `use_frameworks! :linkage => :static`, resulting in a duplication error. This change seems to solve the issue.

Thank you very much!
