### ISSUE TITLE
[Bug]: BrazeDelegate methods are not called if app is not in memory

### ISSUE THREAD

**Issue by Saulenco** [braze-inc/braze-swift-sdk#51]
### Platform

iOS

### Platform Version

iOS 16.1

### Braze SDK Version

5.11.1

### Xcode Version

14.2

### Computer Processor

Apple (M1)

### Repro Rate

100% 

### Steps To Reproduce

after braze is initialised:
```
 func start(in application: UIApplication, options: [UIApplication.LaunchOptionsKey: Any]?) {
        let brazeKey = URLHelper.brazeApiKey
        let endPoint = "sdk.iad-05.braze.com"
        let configuration = Braze.Configuration(
            apiKey: brazeKey,
            endpoint: endPoint
        )
        configuration.sessionTimeout = 60
        configuration.triggerMinimumTimeInterval = 1

        let braze = Braze(configuration: configuration)
        braze.delegate = self
        braze.inAppMessagePresenter = BrazeInAppMessageUI()
        BrazeService.braze = braze
        
        let center = UNUserNotificationCenter.current()
        center.setNotificationCategories(Braze.Notifications.categories)
    }
```

- kill the app
- send in app message with a deep link
- tap on notification
- tap on deep link - nothing happens

### Expected Behavior

braze delegate method shouldOpenURL: should be called, like is called when push is receive when app in in foreground

### Actual Incorrect Behavior

braze delegate method shouldOpenURL: should is not called called at first start .

**Comment by jerielng** [comment]
Hi @Saulenco - thanks for the reproduction steps! Sorry to hear you are not able to trigger a deeplink when the app isn't running.

To make sure I understand the scenario correctly, I wanted to verify that I'm following your same workflow:

For your in-app message, you're using this `Deep Link Into App` feature for your on-click behavior, correct?
![image](https://user-images.githubusercontent.com/16450008/225070162-8c0b9c29-f6ab-4918-88c0-74617799690b.png)

When you have the app closed, you are tapping the push notification on your phone's lock/home screen and expecting to deeplink into the desired location of your app, but that's not happening?

If the above is correct, I'm unable to reproduce the same issue from our end. Could you also provide more details on what the implementation of your `braze(_:shouldOpenURL:)` looks like?

Finally, since killing an app also cuts the connection to the Xcode debugger, are there any other visual cues or logging you can temporarily add to your `braze(_:shouldOpenURL:)` method to verify that it's not being called upon returning? This could help narrow down whether it's an issue with the method not being called or with the deeplink.

**Comment by Saulenco** [comment]
Hi @jerielng,
yes we are using `Deep Link Into App ` and we have a button on in app message that has a `Deep Link Into App `
please see attached image:
![Screenshot 2023-03-15 at 09 12 55](https://user-images.githubusercontent.com/8323284/225233709-e9875212-6c0c-4045-b3e8-861f49cf6d00.png)

and we have 2 scenarios:
**app is running, or it is in background:**
- send a in App Message
- push is Received
- press on push
- in App Message is displayed in app
- touch on the button works as expected and `braze(_:shouldOpenURL:)` is triggered

**app is killed, the app is not in Application stack**
- send a in App Message
- push is Received
- press on push
- in App Message is displayed in app
- touch on the button **doesn't** works as expected and `braze(_:shouldOpenURL:)` is **not** triggered

**Comment by jerielng** [comment]
Thanks for the additional info @Saulenco - unfortunately, we are still unable to reproduce this scenario.

Could you provide further details on your implementation? I notice you are using the following line:
`braze.delegate = self`
* Could you expand more on what class your `self` refers to?
* Could you also provide more insight on how your `BrazeService` is set up since that appears to be a custom implementation?

Might it be possible that the reference to the BrazeDelegate that is being assigned in this `start` function may not be available at the time that your app is starting up and only after all the initialization is complete?

**Comment by oriolpregona** [comment]
Hi guys :)
I believe this is duplicated from this ticket that was closed recently without getting fixed:
https://github.com/braze-inc/braze-swift-sdk/issues/39

We are also experiencing the same issue, deeplinks are broken.
The delegate is assigned, we do it all before didFinishLaunch, etc. Any update on this? 
Thanks!

**Comment by Saulenco** [comment]
so after more digging i have notice that we hold a strong reference to braze window like so:
```
let brazeWindow = UIApplication
            .shared
            .connectedScenes
            .flatMap { ($0 as? UIWindowScene)?.windows ?? [] }
            .first { $0 is BrazeInAppMessageUI.Window }
```

and I have notice that if the app is from "cold start" this somehow disturbes the delegate, if i remove this, or use it as a getter without a strong reference it work as expected.

**Comment by oriolpregona** [comment]
I also have an update. Our url was escaped. This seems to work fine when simulating push notifications on the simulator, but not on real Braze usage. After removing the escaping, it works as expected ✅
