### ISSUE TITLE
[Bug]: ABKInAppMessageWindowController not available in BrazeUI

### ISSUE THREAD

**Issue by jamesormond** [braze-inc/braze-swift-sdk#55]
### Platform

iOS

### Platform Version

iOS 16+

### Braze SDK Version

5.11.2

### Xcode Version

Xcode 14.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

```
if let rootViewController = window?.rootViewController, rootViewController is ABKInAppMessageWindowController {
      return ABKUIUtils.activeApplicationViewController as? UIViewController
}
```
This is code the worked with the `Appboy_iOS_SDK` SDK and in the `BrazeUICompat` SDK, however it does not compile in the `BrazUI` SDK, and there is no documentation available on how to migrate this code.

### Expected Behavior

Compiles

### Actual Incorrect Behavior

Doesn't compile

**Comment by hokstuff** [comment]
Hi @jamesormond,

`ABKInAppMessageWindowController` is a part of the legacy Appboy-iOS-SDK written in Objective-C and is removed in the Braze Swift SDK. Depending on your integration with the class, you may need to refactor your integration to use the existing classes in the Swift SDK instead of this legacy class.

You can take a look at how some of our example apps use the `rootViewController` property in this folder for [some examples](https://github.com/braze-inc/braze-swift-sdk/tree/b8147a77d726f6c75e0ef7efcf0b26f9d1c7b4b5/Examples/Swift) of integrations without that class. Also, referencing the documentation of these two classes might be helpful in your migration: [InAppMessageUI](https://github.com/braze-inc/braze-swift-sdk/blob/main/Sources/BrazeUI/InAppMessageUI/InAppMessageUI.swift) and [InAppMessageUIWindow](https://github.com/braze-inc/braze-swift-sdk/blob/main/Sources/BrazeUI/InAppMessageUI/InAppMessageUIWindow.swift).

**Comment by jamesormond** [comment]
> you may need to refactor your integration to use the existing classes in the Swift SDK instead of this legacy class

I'm having trouble finding the replacements for `ABKInAppMessageWindowController` and `ABKUIUtils.activeApplicationViewController` in the new SDK. Can you specifically point out the replacements?

**Comment by lowip** [comment]
Hi @jamesormond,

The UI layer has changed a lot with the migration to Swift, could you please explain what are you trying to achieve?

I've translated your snippet for the Swift SDK, but without more context, I can't ensure that's what you're looking for:

```swift
if let rootViewController = window?.rootViewController,
   rootViewController is BrazeInAppMessageUI.ViewController {
  return Braze.UIUtils.activeTopmostViewController
  // or
  return Braze.UIUtils.activeRootViewController
}
```

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. As noted above, the UI logic has been completely remade in the Swift SDK so there may be specific APIs that don't have a 1:1 relation, but the functionality still should be possible to do with the new SDK.

If you are still experiencing issues, please include more the information regarding your issue and a link to this Github thread in an email to support@braze.com so our Support team can investigate further. Thanks!

**Comment by jamesormond** [comment]
Thank you! The suggestion from @Iowip above worked!
