### ISSUE TITLE
[Bug]:  App crash on ABKFeedWebViewController in BrazeUICompat

### ISSUE THREAD

**Issue by wajeehUlH** [braze-inc/braze-swift-sdk#57]
### Platform

iOS

### Platform Version

iOS 16.2

### Braze SDK Version

5.10.0

### Xcode Version

14.2 (14C18)

### Computer Processor

Intel

### Repro Rate

100%

### Steps To Reproduce

1) open ABKNewsFeedTableViewController in newsfeedui
2) select option to open web-url 
![Simulator Screen Shot - iPhone 14 - 2023-04-04 at 14 28 40](https://user-images.githubusercontent.com/108662384/229749729-9c6d0e00-58d7-4363-be0b-1c57eadf725e.png)

### Expected Behavior

No crash while sdk calls this method in ABKFeedWebViewController: 
- (void)webView:(WKWebView *)webView
    decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction
    
And line no 143:
   decisionHandler(WKNavigationActionPolicyCancel);

### Actual Incorrect Behavior

App is crashing on 

### Verbose Logs

```shell
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[NSObject webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'
terminating with uncaught exception of type NSException
CoreSimulator 857.14 - Device: iPhone 14 (38F66656-6850-4AB0-89E7-3DA48A3582A1) - Runtime: iOS 16.2 (20C52) - DeviceType: iPhone 14
```

**Comment by lowip** [comment]
Hi @wajeehUlH,

Thank you for reporting this issue. Unfortunately, we are currently unable to reproduce this behavior.

To help with our investigation, can you provide:
- Examples of URLs that trigger the crash
- Links to the NewsFeed dashboard campaigns

Please send that information to support@braze.com, making sure to reference this GitHub issue in the email.

**Comment by hokstuff** [comment]
To add more information, BrazeUICompat (and BrazeKitCompat) are designed to be an in-between step to allow the host app to build during a partial migration, until the ["Full Migration"](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide/) could be completed.

Due to inactivity on this thread, I am closing it out. As noted above, feel free to contact the Support channels for more investigation into your issue so we can help pinpoint the root cause and aid in your migration from AppboyKit to the Swift SDK. Thanks!
